### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by vdhphuc** [jasonodonnell/vault-agent-demo#1]
Hi Jason,
I could deploy the solution to a minikube one-node cluster
$ kubectl -n vault get pods
NAME                                    READY   STATUS    RESTARTS   AGE
vault-0                                 1/1     Running   0          48m
vault-agent-injector-7dcf474d9b-hwpl5   1/1     Running   0          49m

However, I experienced the "x509: certificate signed by unknown authority" error

$ kubectl -n vault exec -it vault-0 -- vault status
Error checking seal status: Get https://127.0.0.1:8200/v1/sys/seal-status: x509: certificate signed by unknown authority
command terminated with exit code 1

I have been across this error before?

Thank you,
Philip

**Comment by jasonodonnell** [comment]
Hi @vdhphuc,

Interesting, this shouldn't happen because `VAULT_CAPATH` env is set in the values file.  You can try the following command:

```bash
kubectl -n vault exec -it vault-0 -- vault status -ca-path=/vault/userconfig/tls-test-server/ca.crt
```

**Comment by vdhphuc** [comment]
Hi @jasonodonnell ,
Thank you for your help.
I ran "export VAULT_SKIP_VERIFY=true", and it worked.
Could you do me a favour to explain how the bootstrap.sh script could be automatically run when the container vault-0 started. I struggle to get my head around that?

Thank you so much,
Philip

**Comment by jasonodonnell** [comment]
Hi @vdhphuc,

Master was stale so I updated it with newer code.  Here are the values that are making the `bootstrap.sh` script run at startup: https://github.com/jasonodonnell/vault-agent-demo/blob/master/values.yaml#L35-L41.

`postStart` takes a command which will run after the pod is ready.  I make the pod go ready by changing the readiness probe to report ready even though it's not initialized or unsealed.  This is useful for demo/testing purposes.

The PR that added the `postStart` feature to Vault Helm can be found here: https://github.com/hashicorp/vault-helm/pull/315.

Hope that helps!

**Comment by vdhphuc** [comment]
That's magic, @jasonodonnell !

Thank you so much! Really appreciated!
